import pyodbc
import pandas as pd
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# -------------------------------------------------------------
# 1️⃣ CONNECT TO SQL SERVER
# -------------------------------------------------------------
conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=ANUJ_LAPTOP;'
    'DATABASE=AUTOMAION;'
    'Trusted_Connection=yes;'
)
print("✅ Connected to SQL Server")

# -------------------------------------------------------------
# 2️⃣ FETCH LATEST KPIs
# -------------------------------------------------------------
kpi_query = """
SELECT TOP 1 *
FROM vw_sales_summary
ORDER BY last_purchase_date DESC
"""
kpi_df = pd.read_sql(kpi_query, conn)
latest = kpi_df.iloc[0]

# -------------------------------------------------------------
# 3️⃣ FETCH TOP 10 CHURN-RISK CUSTOMERS
# -------------------------------------------------------------
churn_query = """
SELECT TOP 10 
    c.customer_id, 
    c.region, 
    c.avg_response_hours,
    c.max_response_hours,
    c.recent_ticket_days,
    c.total_tickets,
    p.churn_probability
FROM vw_customer_features c
JOIN Customer_Churn_Predictions p 
    ON c.customer_id = p.customer_id
ORDER BY p.churn_probability DESC
"""
churn_df = pd.read_sql(churn_query, conn)

conn.close()

# -------------------------------------------------------------
# 4️⃣ FORMAT EMAIL BODY (HTML)
# -------------------------------------------------------------

avg_response = churn_df['avg_response_hours'].mean()
sla = (churn_df['max_response_hours'] <= 24).mean() * 100
fast_ticket_ratio = (churn_df['avg_response_hours'] <= 1).mean() * 100
weekend_ticket_share = (churn_df['recent_ticket_days'] >= 1).mean() * 100

html_body = f"""
<h2>📊 Daily Customer Support & Churn Report — {datetime.now().strftime('%Y-%m-%d')}</h2>

<h3>🔹 Key Support KPIs</h3>
<ul>
  <li><b>Average Response Time:</b> {avg_response:.2f} hours</li>
  <li><b>SLA Compliance:</b> {sla:.2f}%</li>
  <li><b>Fast Ticket Ratio:</b> {fast_ticket_ratio:.2f}%</li>
  <li><b>Weekend Ticket Share:</b> {weekend_ticket_share:.2f}%</li>
</ul>

<h3>🚨 Top 10 At-Risk Customers</h3>
{churn_df.to_html(index=False, border=0)}

<p style='font-size:12px;color:gray;'>
This report was automatically generated by the Customer Retention Intelligence System.<br>
© {datetime.now().year}
</p>
"""

# -------------------------------------------------------------
# 5️⃣ CONFIGURE EMAIL DETAILS
# -------------------------------------------------------------
sender = "anuj.1526@gmail.com"
password = "enuf wjjt qgrs agic"
receiver = "anujup717@gmail.com"

msg = MIMEMultipart()
msg["From"] = sender
msg["To"] = receiver
msg["Subject"] = f"Daily Support KPIs & Churn Report — {datetime.now().strftime('%d %b %Y')}"

msg.attach(MIMEText(html_body, "html"))

# -------------------------------------------------------------
# 6️⃣ SEND EMAIL USING SMTP
# -------------------------------------------------------------
try:
    smtp = smtplib.SMTP("smtp.gmail.com", 587)  # OR smtp.gmail.com
    smtp.starttls()
    smtp.login(sender, password)
    smtp.send_message(msg)
    smtp.quit()
    print("📨 Email sent successfully!")
except Exception as e:
    print("❌ Failed to send email:", e)
